# Generated by Django 5.1.1 on 2024-09-05 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Realisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('resume', models.TextField()),
                ('date_sortie', models.DateField()),
                ('genre', models.CharField(max_length=100)),
                ('url_affiche', models.URLField()),
                ('rating', models.FloatField()),
                ('acteurs', models.ManyToManyField(to='films.acteur')),
                ('realisateur', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='films.realisateur')),
            ],
        ),
    ]
