# Generated by Django 5.1 on 2024-09-10 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='date_sortie',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='genre',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='rating',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='resume',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='url_affiche',
            field=models.URLField(null=True),
        ),
    ]
